org: luka7711
app: api
service: api

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  app-api:
    handler: handler.handler
    events:
      -http:
        path: /
        method: get
